palavras_faceis = ['CANETA', 'CARRO', 'CASA', 'FILHO', 'JOVEM', 'LIVRO', 'PINCEL', 'MESA', 'MORTE', 'TERRA', 'AGUA', 'AR', 'FOGO', 'DIA']

palavras_medias = ['COMPUTADOR', 'ESPIRITO', 'ESCURO', 'INIMIGO', 'INFERNO', 'CADEIRA', 'BICICLETA', 'PESCADOR', 'SOLTEIRO', 'CASADO']

palavras_dificeis = ['PARALELEPIPEDO', 'CAMIONETE', 'MARCENEIRO', 'ONOMATOPEIA', 'XENOFOBIA', 'EPIFANIA', 'CATARSE', 'RADIOLOGIA', 'SINTETIZADOR', 'EUFEMISMO']